apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

helmCharts:
  - name: tempo-distributed
    repo: https://grafana.github.io/helm-charts
    version: 1.33.0
    releaseName: tempo
    namespace: observability
    valuesFile: helm-values.yaml
